# -*- coding: utf-8 -*-
"""__init__.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lPes4pQFCHzU-YBVecgCFiXR72UNmHIq
"""

version=1.0

