# -*- coding: utf-8 -*-
"""mylib

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TaAM4anL_RbwA8e6Ah_omJ7fOWNs2JNS
"""

# mylib.py 모듈 만들어보기 (안에 두 개의 함수)

def add_txt(t1,t2):
  return t1 + ':' + t2

def reverse(x,y,z):
  return z,y,x